apiVersion: v1
kind: Template
labels:
  template: cd-docgen
  app: '${PROJECT}-docgen'
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        service.alpha.openshift.io/dependencies: '[]'
      name: docgen
    spec:
      ports:
      -   name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: '${PROJECT}-docgen'
        deploymentconfig: docgen
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: 'docgen'
    spec:
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        app: '${PROJECT}-docgen'
        deploymentconfig: 'docgen'
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: '${PROJECT}-docgen'
            deploymentconfig: 'docgen'
            env: 'cd'
        spec:
          containers:
            - image: 'cd/docgen:latest'
              imagePullPolicy: IfNotPresent
              name: 'docgen'
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                limits:
                  memory: '${MEMORY_LIMIT}'
                requests:
                  memory: '${MEMORY_REQUEST}'
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              env:
                - name: BITBUCKET_URL
                  value: 'https://${BITBUCKET_HOST}'
                - name: BITBUCKET_USERNAME
                  valueFrom:
                    secretKeyRef:
                      key: username
                      name: cd-user-with-password
                - name: BITBUCKET_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: cd-user-with-password
                - name: BITBUCKET_DOCUMENT_TEMPLATES_PROJECT
                  value: opendevstack
                - name: BITBUCKET_DOCUMENT_TEMPLATES_REPO
                  value: ods-document-generation-templates
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - 'docgen'
            from:
              kind: ImageStreamTag
              name: 'docgen:latest'
              namespace: cd
          type: ImageChange
parameters:
  - name: PROJECT
    displayName: Application
    description: The name of the application project.
    required: true
  - name: BITBUCKET_HOST
    displayName: Application
    description: The host of your bitbucket server.
    required: true
  - name: MEMORY_LIMIT
    displayName: Memory Limit
    description: Maximum amount of memory available for the container.
    value: 512Mi
    required: true
  - name: MEMORY_REQUEST
    displayName: Memory Request
    description: Minimum amount of memory requested for the container.
    value: 256Mi
    required: true
