apiVersion: v1
kind: Template
metadata:
  name: jenkins-slave-scala
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: jenkins-slave-scala
    labels:
      app: jenkins-slave-scala
  spec:
    dockerImageRepository: jenkins-slave-scala
    lookupPolicy:
      local: false
